apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: aibrix-custom-proxy-config
  namespace: aibrix-system
spec:
  provider:
    kubernetes:
      envoyService:
        patch:
          value:
            spec:
              type: ClusterIP
              ipFamilies:
              - IPv4    # Only IPv4
              ipFamilyPolicy: SingleStack  # Changed from PreferDualStack to SingleStack
      envoyDeployment:
        container:
          resources:
            requests:
              cpu: 2
              memory: 8Gi
            limits:
              cpu: 2
              memory: 8Gi
          image: aibrix-container-registry-cn-beijing.cr.volces.com/envoyproxy/envoy:distroless-v1.31.0