apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: vllm
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2025-03-12T21:28:53Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
    environment: router
    release: router
  name: vllm-deployment-router
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      environment: router
      release: router
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        environment: router
        release: router
    spec:
      containers:
      - args:
        - --host
        - 0.0.0.0
        - --port
        - "8000"
        - --service-discovery
        - k8s
        - --k8s-namespace
        - default
        - --k8s-label-selector
        - environment=test,release=test
        - --routing-logic
        - session
        - --session-key
        - x-user-id
        - --engine-stats-interval
        - "15"
        - --request-stats-window
        - "60"
        image: aibrix-container-registry-cn-beijing.cr.volces.com/lmcache/lmstack-router:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 2000m
            memory: 8Gi
          requests:
            cpu: 2000m
            memory: 8Gi
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: router-container
        ports:
        - containerPort: 8000
          name: router-cport
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: vllm-router-service-account
      serviceAccountName: vllm-router-service-account
      terminationGracePeriodSeconds: 30